---
- name: Install Apache on Ubuntu
  hosts: your-server-hostname
  become: true
  become_method: sudo # Use the "sudo" method for privilege escalation
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: true

    - name: Install Apache web server
      apt:
        name: apache2
        state: present
      become: true
      notify:
        - Start Apache service

  handlers:
    - name: Start Apache service
      service:
        name: apache2
        state: started
      become: true
# ansible-playbook apache-install.yml --ask-become-pass
